Release/2021 09 10 19 17 38
Bandwidth/python-sdk pull request #29
Opened 2021-09-10 19:20 UTC by ajrice6713

2021-09-10 20:50 UTC, hamermike requested changes

2021-09-10 20:50 UTC, hamermike commented on tests/integration/api_tests.py
> +        time.sleep(1) #No guarantee that the info will be immediately available
```suggestion
        time.sleep(1) #No guarantee that the info will be immediately available
```
I don't believe this is needed. We've been running other languages without this in here without issue.

2021-09-10 20:50 UTC, hamermike commented on tests/integration/api_tests.py
> +        self.assertTrue(len(response.body.call_id) > 1)
```suggestion
        self.assertTrue(len(response.body.call_id) > 1)
```
Can we test the remainder of the response body values too? And the status code? 🥇

2021-09-13 19:06 UTC, ckoegel submitted a review, later dismissed

2021-09-14 14:50 UTC, hamermike approved these changes

2021-09-14 17:24 UTC, ckoegel approved these changes

2021-09-14 20:07 UTC, hamermike approved these changes

2021-09-14 20:10 UTC, ckoegel approved these changes

2021-09-14 20:10 UTC, merged