DX-2460 Update setup.py to use requirements.txt
Bandwidth/python-sdk pull request #52
Opened 2022-03-07 21:55 UTC by ckoegel

2022-03-07 22:00 UTC, hamermike submitted a review, later dismissed

2022-03-08 14:30 UTC, ajrice6713 requested changes

2022-03-08 14:30 UTC, ajrice6713 commented on .github/workflows/test.yaml
> +      run: pip install -r test-requirements.txt
I think the proper naming convention for this file is `requirements_dev.txt`

2022-03-08 15:02 UTC, ajrice6713 submitted a review, later dismissed

2022-03-08 15:12 UTC, ajrice6713 approved these changes

2022-03-08 15:16 UTC, hamermike approved these changes

2022-03-08 15:31 UTC, merged